up

diff --git a/.github/workflows/dependabot-auto-merge.yml b/.github/workflows/dependabot-auto-merge.yml
--- a/.github/workflows/dependabot-auto-merge.yml
+++ b/.github/workflows/dependabot-auto-merge.yml
@@ -19,8 +19,12 @@ jobs:
         id: check_approval
         run: |
           pr_number=${{ github.event.pull_request.number }}
-          repo_url="https://github.com/ryotamurakami/${{ github.repository }}/pulls/${pr_number}/reviews"
+          repo_url="https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/reviews"  # Changed this line
           response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $repo_url)
+          if [ "$response" == "" ]; then
+            echo "Failed to fetch PR reviews."
+            exit 1
+          fi
           approved=$(echo "$response" | jq -r 'any(.[]; .state == "APPROVED")')
           echo "APPROVED=$approved" >> $GITHUB_ENV
         env:
